### ISSUE TITLE
the bot buys if the owner buys his shares, even if the account is not new

### ISSUE THREAD

**Issue by ETHSev** [jamesbachini/FriendTech-Trading-Bot#3]
Hello Friend Thanks for the Bot It Works Well.
There is only one thing that I would like you to help me change since I am not a good programmer. It is that the bot buys when the owner makes a new purchase, I would like a new condition to be set. If the owner bought the action before, in that case the bot does not buy. buy only when it is really a new account. thank you

**Comment by jamesbachini** [comment]
I can't do individual customizations to the code, sorry
